import {env} from 'cloudflare:workers';
export const dynamic='force-dynamic';
function db(){if(!env.DB)throw Error('Database unavailable');return env.DB}
function json(data:any,status=200){return Response.json(data,{status})}
async function handle(req:Request){try{
 const user=req.headers.get('oai-authenticated-user-id');if(!user)return json({error:'Please sign in to your private workspace.'},401);
 if(req.method!=='GET'&&req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)return json({error:'Invalid request origin'},403);
 const path=new URL(req.url).pathname.split('/').filter(Boolean).slice(1);const store=db();
 if(path[0]==='files'&&req.method==='GET'){
 const f:any=await store.prepare('SELECT e.* FROM evidence e JOIN audits a ON a.id=e.audit_id WHERE e.id=? AND a.owner=?').bind(path[1],user).first();if(!f)return json({error:'File not found'},404);const object=await env.BUCKET!.get(f.id);if(!object)return json({error:'File unavailable'},404);
 const safeImage=['image/jpeg','image/png','image/webp','image/gif'].includes(f.mime);
 return new Response(object.body,{headers:{'Content-Type':safeImage?f.mime:'application/octet-stream','Content-Disposition':`${safeImage?'inline':'attachment'}; filename*=UTF-8''${encodeURIComponent(f.name)}`,'X-Content-Type-Options':'nosniff','Cache-Control':'private, no-store'}});
 }
 if(path[0]!=='audits')return json({error:'Not found'},404);
 if(path.length===1){if(req.method==='GET'){const r=await store.prepare('SELECT data FROM audits WHERE owner=? ORDER BY updated DESC').bind(user).all();return json(r.results.map((x:any)=>JSON.parse(x.data)))}
 if(req.method==='POST'){const b:any=await req.json();if(!b.name?.trim()||!b.location?.trim())return json({error:'Site name and location are required'},400);const id=b.id||crypto.randomUUID();const old:any=b.id?await store.prepare('SELECT data FROM audits WHERE id=? AND owner=?').bind(id,user).first():null;if(b.id&&!old)return json({error:'Audit not found'},404);const previous=old?JSON.parse(old.data):{};const a={...previous,id,name:String(b.name).slice(0,300),location:String(b.location).slice(0,500),type:b.type||'Factory',date:b.date||'',auditor:b.auditor||'',status:b.status||'In progress',summary:b.summary||'',coverage:previous.coverage||{}};await store.prepare('INSERT INTO audits (id,owner,data,updated) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,updated=excluded.updated').bind(id,user,JSON.stringify(a),new Date().toISOString()).run();return json(a)} }
 const id=path[1];const record:any=await store.prepare('SELECT data FROM audits WHERE id=? AND owner=?').bind(id,user).first();if(!record)return json({error:'Audit not found'},404);
 if(path.length===2){if(req.method==='GET'){const f=await store.prepare('SELECT data FROM findings WHERE audit_id=? ORDER BY rowid').bind(id).all();const e=await store.prepare('SELECT * FROM evidence WHERE audit_id=? ORDER BY rowid').bind(id).all();return json({findings:f.results.map((x:any)=>JSON.parse(x.data)),files:e.results})}if(req.method==='PATCH'){const b:any=await req.json();const a={...JSON.parse(record.data),coverage:b.coverage||{}};await store.prepare('UPDATE audits SET data=?,updated=? WHERE id=? AND owner=?').bind(JSON.stringify(a),new Date().toISOString(),id,user).run();return json(a)}}
 if(path[2]==='findings'&&req.method==='POST'){const b:any=await req.json();if(!b.title?.trim()||!b.notes?.trim())return json({error:'A title and observations are required'},400);if(!['Critical','High','Medium','Low','Informational'].includes(b.severity))return json({error:'Invalid risk level'},400);const fid=b.id||crypto.randomUUID();if(b.id&&!await store.prepare('SELECT id FROM findings WHERE id=? AND audit_id=?').bind(fid,id).first())return json({error:'Finding not found'},404);const f={id:fid,title:b.title,notes:b.notes,category:b.category,severity:b.severity,status:b.status,recommendation:b.recommendation||'',owner:b.owner||'',due:b.due||''};await store.prepare('INSERT INTO findings (id,audit_id,data) VALUES (?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data').bind(fid,id,JSON.stringify(f)).run();return json(f)}
 if(path[2]==='files'&&req.method==='POST'){if(!env.BUCKET)throw Error('File storage unavailable');const form=await req.formData();const file=form.get('file');if(!file||typeof file==='string')return json({error:'Choose a file'},400);if(file.size>20*1024*1024)return json({error:'Files must be under 20 MB'},400);const fid=crypto.randomUUID();await env.BUCKET.put(fid,file.stream(),{httpMetadata:{contentType:file.type||'application/octet-stream'}});try{await store.prepare('INSERT INTO evidence (id,audit_id,name,mime,size) VALUES (?,?,?,?,?)').bind(fid,id,file.name,file.type||'application/octet-stream',file.size).run()}catch(e){await env.BUCKET.delete(fid);throw e}return json({id:fid})}
 return json({error:'Not found'},404);
 }catch(e){console.error('Audit storage error',e);return json({error:'Your workspace is temporarily unavailable. Your input has been kept. Please retry.'},503)}}
export const GET=handle;export const POST=handle;export const PATCH=handle;
