import {Document,Packer,Paragraph,TextRun,HeadingLevel,ImageRun,ExternalHyperlink,Footer,PageNumber} from 'docx';
const areas=['Site & facilities','Network & connectivity','Servers & cloud','Cybersecurity','Workplace & applications','OT & production','IT operations','Integration roadmap'];
export async function buildReport(site:any,findings:any[],files:any[],imageLoader?:(f:any)=>Promise<any>,origin=''){
 const p=(text:string)=>new Paragraph({text:String(text||'Not recorded'),spacing:{after:160}});
 const h=(text:string)=>new Paragraph({text,heading:HeadingLevel.HEADING_1,spacing:{before:320,after:180}});
 const children:any[]=[new Paragraph({text:'FIELDBOOK · IT ACQUISITION AUDIT',spacing:{after:500}}),new Paragraph({text:site.name,heading:HeadingLevel.TITLE}),p('Acquisition IT assessment'),p(`${site.location} | ${site.type} | ${site.date}`),p(`Lead auditor: ${site.auditor||'Not specified'}`),p(`Status: ${site.status}`),h('1. Executive summary'),p(site.summary),h('2. Audit scope & coverage'),...areas.map(a=>p(`${a}: ${site.coverage?.[a]?'Reviewed':'Not yet reviewed'}`)),h('3. Findings & risk assessment'),p(`${findings.length} findings. ${findings.filter(f=>['Critical','High'].includes(f.severity)&&f.status!=='Resolved').length} open high or critical risks.`)];
 for(const [i,f] of findings.entries())children.push(new Paragraph({text:`${i+1}. ${f.title}`,heading:HeadingLevel.HEADING_2}),p(`${f.category} | ${f.severity} risk | ${f.status}`),p(f.notes),p(`Recommended improvement: ${f.recommendation||'Not recorded'}`),p(`Owner: ${f.owner||'Unassigned'} | Target: ${f.due||'Not set'}`));
 children.push(h('4. Action plan'));for(const f of findings.filter(f=>f.recommendation))children.push(p(`${f.title}\n${f.recommendation}\nOwner: ${f.owner||'Unassigned'} · Due: ${f.due||'Not set'} · ${f.status}`));
 children.push(h('5. Evidence register & photographs'));if(!files.length)children.push(p('No evidence attached.'));
 for(const [i,f] of files.entries()){children.push(new Paragraph({text:`Evidence ${i+1}: ${f.name}`,heading:HeadingLevel.HEADING_2}),p(`${f.mime} · ${(f.size/1024).toFixed(0)} KB${f.caption?' · '+f.caption:''}`));if(f.mime.startsWith('image/')&&imageLoader){const image=await imageLoader(f);children.push(new Paragraph({children:[new ImageRun({data:image.data,type:'png',transformation:{width:image.width,height:image.height}})]}));}children.push(new Paragraph({children:[new ExternalHyperlink({link:origin+'/api/files/'+f.id,children:[new TextRun({text:'Open original evidence (workspace access required)',style:'Hyperlink'})]})]}));}
 return new Document({creator:'Fieldbook',title:`IT Audit — ${site.name}`,styles:{default:{document:{run:{font:'Calibri',size:22,color:'253B32'},paragraph:{spacing:{after:140}}}}},sections:[{properties:{page:{margin:{top:1100,bottom:1100,left:1100,right:1100}}},footers:{default:new Footer({children:[new Paragraph({children:[new TextRun('CONFIDENTIAL · IT Audit     '),new TextRun({children:[PageNumber.CURRENT]})]})]})},children}]});
}
export async function exportReport(site:any,findings:any[],files:any[]){
 const document=await buildReport(site,findings,files,async f=>{const response=await fetch('/api/files/'+f.id);if(!response.ok)throw Error('Could not load '+f.name);const blob=await response.blob();const bitmap=await createImageBitmap(blob).catch(()=>{throw Error('Image format cannot be embedded: '+f.name+'. Please upload a JPEG or PNG version.');});const scale=Math.min(1,560/bitmap.width,650/bitmap.height);const canvas=window.document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d')!.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const png=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('Image conversion failed')),'image/png'));return {data:new Uint8Array(await png.arrayBuffer()),width:canvas.width,height:canvas.height}},location.origin);
 const blob=await Packer.toBlob(document);const url=URL.createObjectURL(blob);const a=window.document.createElement('a');a.href=url;a.download=site.name.replace(/[^a-z0-9 -]/gi,'')+' - IT Audit.docx';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);
}
