import {Document,Packer,Paragraph,TextRun,HeadingLevel,ImageRun,ExternalHyperlink,Footer,PageNumber} from 'docx';
import {readFile} from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';
import {areas} from './templates.js';
export async function makeReport(a,uploads,origin){
 const p=(s)=>new Paragraph({text:String(s||'Not recorded'),spacing:{after:140}});
 const h=(s,level=HeadingLevel.HEADING_1)=>new Paragraph({text:s,heading:level,keepNext:true,spacing:{before:300,after:160}});
 const areaName=id=>areas.find(x=>x.id===id)?.name||'General evidence';
 const children=[new Paragraph({text:`IT Acquisition Audit ${a.name}`,heading:HeadingLevel.TITLE}),p('Assessment of the acquired site, observed risks and recommended integration actions.'),p(`Location: ${a.location}\nSite type: ${a.type}\nAudit date: ${a.date||'Not recorded'}\nLead auditor: ${a.auditor||'Not recorded'}\nStatus: ${a.status}`),h('Executive summary'),p(a.summary),p(`${a.findings.length} confirmed findings. ${a.findings.filter(f=>['High','Critical'].includes(f.severity)&&!['Resolved','Accepted'].includes(f.status)).length} open high or critical risks. ${a.checks.filter(c=>c.status!=='Not reviewed').length} of ${a.checks.length} checks reviewed.`),h('Scope and review results'),p('Checklist prompts guide evidence collection. An unreviewed item is not a confirmed defect. Risk ratings and recommendations reflect the auditor’s recorded assessment.')];
 for(const area of areas){children.push(h(area.name,HeadingLevel.HEADING_2));for(const c of a.checks.filter(c=>c.area===area.id)){children.push(new Paragraph({children:[new TextRun({text:`${c.title} — ${c.status}`,bold:true})],keepNext:!!c.notes}),p(`Review: ${c.prompt}`));if(c.notes)children.push(p(`Review notes: ${c.notes}`));}}
 children.push(h('Confirmed findings'));
 if(!a.findings.length)children.push(p('No confirmed findings have been recorded.'));
 for(const [i,f] of a.findings.entries()){children.push(h(`${i+1} ${f.title}`,HeadingLevel.HEADING_2),p(`${areaName(f.area)} · ${f.severity} risk · ${f.status}`),p(`Observations and comments\n${f.notes}`),p(`Recommended improvement\n${f.recommendation||'Not recorded'}`),p(`Action owner: ${f.owner||'Unassigned'}\nTarget date: ${f.due||'Not set'}\nChecklist reference: ${f.templateId||'Custom finding'}`));const evidence=a.files.filter(x=>x.finding_id===f.id);if(evidence.length)children.push(p('Evidence: '+evidence.map(x=>x.name).join(', ')));}
 children.push(h('Action plan'));
 for(const f of a.findings){children.push(h(f.title,HeadingLevel.HEADING_2),p(`${f.recommendation||'No improvement recorded'}\nOwner: ${f.owner||'Unassigned'} · Due: ${f.due||'Not set'} · Status: ${f.status}`));}
 if(!a.findings.length)children.push(p('No actions recorded.'));
 children.push(h('Evidence register and photographs'));
 if(!a.files.length)children.push(p('No evidence attached.'));
 for(const [i,f] of a.files.entries()){children.push(h(`Evidence ${i+1} ${f.name}`,HeadingLevel.HEADING_2),p(`${areaName(f.area)} · ${(f.size/1024).toFixed(0)} KB · Uploaded ${f.created_at.slice(0,10)}`));if(f.finding_id)children.push(p('Finding: '+(a.findings.find(x=>x.id===f.finding_id)?.title||'Unlinked')));if(f.caption)children.push(p(f.caption));if(f.image){const bytes=await readFile(path.join(uploads,f.id+'.png'));const meta=await sharp(bytes).metadata();const scale=Math.min(1,540/meta.width,620/meta.height);children.push(new Paragraph({children:[new ImageRun({type:'png',data:bytes,transformation:{width:Math.round(meta.width*scale),height:Math.round(meta.height*scale)}})],spacing:{after:180}}));}children.push(new Paragraph({children:[new ExternalHyperlink({link:`${origin}/api/files/${f.id}`,children:[new TextRun({text:'Download original attachment (server access required)',style:'Hyperlink'})]})]}));}
 children.push(h('Checklist references'),p('The practical acquisition checklist is informed by NIST CSF 2.0 and CISA guidance. It is not a certification or a complete assessment of legal obligations.'),p('https://www.nist.gov/cyberframework'),p('https://www.cisa.gov/stopransomware/ransomware-guide'));
 const document=new Document({creator:'Fieldbook',title:`IT Acquisition Audit ${a.name}`,styles:{default:{document:{run:{font:'Calibri',size:22,color:'243A32'},paragraph:{spacing:{after:140}}}},paragraphStyles:[{id:'Title',name:'Title',basedOn:'Normal',run:{size:42,bold:true,color:'000000'},paragraph:{spacing:{after:300}}},{id:'Heading1',name:'Heading 1',basedOn:'Normal',next:'Normal',run:{size:30,bold:true,color:'205743'},paragraph:{keepNext:true}},{id:'Heading2',name:'Heading 2',basedOn:'Normal',next:'Normal',run:{size:25,bold:true,color:'263E32'},paragraph:{keepNext:true}}]},sections:[{properties:{page:{size:{width:12240,height:15840},margin:{top:1080,bottom:1080,left:1080,right:1080}}},footers:{default:new Footer({children:[new Paragraph({children:[new TextRun('CONFIDENTIAL · FIELDBOOK     '),new TextRun({children:[PageNumber.CURRENT]})]})]})},children}]});
 return Packer.toBuffer(document);
}
